// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MohCovidInsights.Infrastructure.Persistence;

#nullable disable

namespace MohCovidInsights.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("MohCovidInsights.Domain.Entities.DatasetSyncRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("completed_at");

                    b.Property<string>("DatasetId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("dataset_id");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT")
                        .HasColumnName("failure_reason");

                    b.Property<string>("PayloadHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("payload_hash");

                    b.Property<int>("RowCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("row_count");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("DatasetId", "StartedAt")
                        .HasDatabaseName("ix_sync_runs_dataset_started");

                    b.ToTable("sync_runs", (string)null);
                });

            modelBuilder.Entity("MohCovidInsights.Domain.Entities.WeeklyObservation", b =>
                {
                    b.Property<int>("EpiWeekKey")
                        .HasColumnType("INTEGER")
                        .HasColumnName("epi_week_key");

                    b.Property<string>("MetricCode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("metric_code");

                    b.Property<string>("Dimension")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("dimension");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("EpiWeekKey", "MetricCode", "Dimension");

                    b.HasIndex("MetricCode", "EpiWeekKey")
                        .HasDatabaseName("ix_observations_metric_week");

                    b.ToTable("observations", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
